# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\main_doctor_position_dialog_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PositionDialog(object):
    def setupUi(self, PositionDialog):
        PositionDialog.setObjectName("PositionDialog")
        PositionDialog.resize(400, 300)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        PositionDialog.setFont(font)
        self.main_layout = QtWidgets.QVBoxLayout(PositionDialog)
        self.main_layout.setContentsMargins(10, 10, 10, 10)
        self.main_layout.setSpacing(10)
        self.main_layout.setObjectName("main_layout")
        self.lbl_add_new_position = QtWidgets.QLabel(PositionDialog)
        self.lbl_add_new_position.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_add_new_position.setObjectName("lbl_add_new_position")
        self.main_layout.addWidget(self.lbl_add_new_position)
        self.lbl_name = QtWidgets.QLabel(PositionDialog)
        self.lbl_name.setObjectName("lbl_name")
        self.main_layout.addWidget(self.lbl_name)
        self.lnedit_name = QtWidgets.QLineEdit(PositionDialog)
        self.lnedit_name.setAlignment(QtCore.Qt.AlignCenter)
        self.lnedit_name.setObjectName("lnedit_name")
        self.main_layout.addWidget(self.lnedit_name)
        self.wdgt_dialog_buttons = QtWidgets.QWidget(PositionDialog)
        self.wdgt_dialog_buttons.setObjectName("wdgt_dialog_buttons")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.wdgt_dialog_buttons)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pshbtn_save = QtWidgets.QPushButton(self.wdgt_dialog_buttons)
        self.pshbtn_save.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pshbtn_save.setObjectName("pshbtn_save")
        self.horizontalLayout.addWidget(self.pshbtn_save)
        self.pshbtn_cancel = QtWidgets.QPushButton(self.wdgt_dialog_buttons)
        self.pshbtn_cancel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pshbtn_cancel.setObjectName("pshbtn_cancel")
        self.horizontalLayout.addWidget(self.pshbtn_cancel)
        self.main_layout.addWidget(self.wdgt_dialog_buttons)
        self.main_layout.setStretch(0, 1)
        self.main_layout.setStretch(1, 1)
        self.main_layout.setStretch(2, 1)
        self.main_layout.setStretch(3, 1)

        self.retranslateUi(PositionDialog)
        QtCore.QMetaObject.connectSlotsByName(PositionDialog)

    def retranslateUi(self, PositionDialog):
        _translate = QtCore.QCoreApplication.translate
        PositionDialog.setWindowTitle(_translate("PositionDialog", "Dialog"))
        self.lbl_add_new_position.setText(_translate("PositionDialog", "Add New Position"))
        self.lbl_name.setText(_translate("PositionDialog", "Name:"))
        self.lnedit_name.setPlaceholderText(_translate("PositionDialog", "Enter name..."))
        self.pshbtn_save.setText(_translate("PositionDialog", "Save"))
        self.pshbtn_cancel.setText(_translate("PositionDialog", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PositionDialog = QtWidgets.QDialog()
    ui = Ui_PositionDialog()
    ui.setupUi(PositionDialog)
    PositionDialog.show()
    sys.exit(app.exec_())
