# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\main_login_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import resource_rc


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(500, 500)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        Login.setFont(font)
        Login.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Login.setModal(True)
        self.main_layout = QtWidgets.QVBoxLayout(Login)
        self.main_layout.setContentsMargins(10, 10, 10, 10)
        self.main_layout.setSpacing(10)
        self.main_layout.setObjectName("main_layout")
        self.pxmp_logo = QtWidgets.QLabel(Login)
        self.pxmp_logo.setText("")
        self.pxmp_logo.setAlignment(QtCore.Qt.AlignCenter)
        self.pxmp_logo.setObjectName("pxmp_logo")
        self.main_layout.addWidget(self.pxmp_logo)
        self.lbl_username = QtWidgets.QLabel(Login)
        self.lbl_username.setObjectName("lbl_username")
        self.main_layout.addWidget(self.lbl_username)
        self.lnedit_username = QtWidgets.QLineEdit(Login)
        self.lnedit_username.setAlignment(QtCore.Qt.AlignCenter)
        self.lnedit_username.setObjectName("lnedit_username")
        self.main_layout.addWidget(self.lnedit_username)
        self.lbl_password = QtWidgets.QLabel(Login)
        self.lbl_password.setObjectName("lbl_password")
        self.main_layout.addWidget(self.lbl_password)
        self.lnedit_password = QtWidgets.QLineEdit(Login)
        self.lnedit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lnedit_password.setAlignment(QtCore.Qt.AlignCenter)
        self.lnedit_password.setObjectName("lnedit_password")
        self.main_layout.addWidget(self.lnedit_password)
        self.pshbtn_login = QtWidgets.QPushButton(Login)
        self.pshbtn_login.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pshbtn_login.setObjectName("pshbtn_login")
        self.main_layout.addWidget(self.pshbtn_login)
        self.pshbtn_exit = QtWidgets.QPushButton(Login)
        self.pshbtn_exit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pshbtn_exit.setObjectName("pshbtn_exit")
        self.main_layout.addWidget(self.pshbtn_exit)
        self.main_layout.setStretch(0, 5)
        self.main_layout.setStretch(1, 1)
        self.main_layout.setStretch(2, 1)
        self.main_layout.setStretch(3, 1)
        self.main_layout.setStretch(4, 1)
        self.main_layout.setStretch(5, 1)
        self.main_layout.setStretch(6, 1)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Login"))
        self.lbl_username.setText(_translate("Login", "Username:"))
        self.lnedit_username.setPlaceholderText(_translate("Login", "Enter username..."))
        self.lbl_password.setText(_translate("Login", "Password:"))
        self.lnedit_password.setPlaceholderText(_translate("Login", "Enter password..."))
        self.pshbtn_login.setText(_translate("Login", "Login"))
        self.pshbtn_exit.setText(_translate("Login", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login = QtWidgets.QDialog()
    ui = Ui_Login()
    ui.setupUi(Login)
    Login.show()
    sys.exit(app.exec_())
