# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\setup_login_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DevLogin(object):
    def setupUi(self, DevLogin):
        DevLogin.setObjectName("DevLogin")
        DevLogin.resize(400, 300)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        DevLogin.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/logo-removebg.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DevLogin.setWindowIcon(icon)
        DevLogin.setModal(True)
        self.main_layout = QtWidgets.QVBoxLayout(DevLogin)
        self.main_layout.setContentsMargins(10, 10, 10, 10)
        self.main_layout.setSpacing(10)
        self.main_layout.setObjectName("main_layout")
        self.lbl_username = QtWidgets.QLabel(DevLogin)
        self.lbl_username.setObjectName("lbl_username")
        self.main_layout.addWidget(self.lbl_username)
        self.lnedit_username = QtWidgets.QLineEdit(DevLogin)
        self.lnedit_username.setAlignment(QtCore.Qt.AlignCenter)
        self.lnedit_username.setObjectName("lnedit_username")
        self.main_layout.addWidget(self.lnedit_username)
        self.lbl_password = QtWidgets.QLabel(DevLogin)
        self.lbl_password.setObjectName("lbl_password")
        self.main_layout.addWidget(self.lbl_password)
        self.lnedit_password = QtWidgets.QLineEdit(DevLogin)
        self.lnedit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lnedit_password.setAlignment(QtCore.Qt.AlignCenter)
        self.lnedit_password.setObjectName("lnedit_password")
        self.main_layout.addWidget(self.lnedit_password)
        self.line = QtWidgets.QFrame(DevLogin)
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.main_layout.addWidget(self.line)
        self.pshbtn_login = QtWidgets.QPushButton(DevLogin)
        self.pshbtn_login.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pshbtn_login.setObjectName("pshbtn_login")
        self.main_layout.addWidget(self.pshbtn_login)
        self.main_layout.setStretch(0, 1)
        self.main_layout.setStretch(1, 1)
        self.main_layout.setStretch(2, 1)
        self.main_layout.setStretch(3, 1)
        self.main_layout.setStretch(4, 1)
        self.main_layout.setStretch(5, 1)

        self.retranslateUi(DevLogin)
        QtCore.QMetaObject.connectSlotsByName(DevLogin)

    def retranslateUi(self, DevLogin):
        _translate = QtCore.QCoreApplication.translate
        DevLogin.setWindowTitle(_translate("DevLogin", "Authorize"))
        self.lbl_username.setText(_translate("DevLogin", "Username:"))
        self.lnedit_username.setPlaceholderText(_translate("DevLogin", "Enter username..."))
        self.lbl_password.setText(_translate("DevLogin", "Password:"))
        self.lnedit_password.setPlaceholderText(_translate("DevLogin", "Enter password..."))
        self.pshbtn_login.setText(_translate("DevLogin", "Login"))
import dev_resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DevLogin = QtWidgets.QDialog()
    ui = Ui_DevLogin()
    ui.setupUi(DevLogin)
    DevLogin.show()
    sys.exit(app.exec_())
